config/routes.rb
Rails.application.routes.draw do
  get 'histories/index'

  get 'categories/index'

  resources :home
  resources :accounts
  resources :categories
  resources :histories
  # get 'accounts/index'
  # get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates :date, presence: true
  validates :category, presence: true
  validates :purpose, presence: true
  validates :money, presence: true
  default_scope -> { order(date: :asc) }

  scope :search_by_month, ->(beginning_of_month) {
    where('date >= ?', beginning_of_month)
  }

  scope :search_by_year_and_month, ->(year, month) {
    where(year: year).where(month: month)
  }

  scope :total_amount, -> {
    pluck(:money).sum
  }

  scope :only_green, -> {
    where(purpose: "仕事・勉強")
  }

  scope :only_yellow, -> {
    where(purpose: "生活費")
  }

  scope :only_red, -> {
    where(purpose: "趣味・娯楽")
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @today = Date.today
    @year = @today.year
    @month = @today.month
    @accounts = Account.all.search_by_month(@today.beginning_of_month)
    set_sum_money

    @categories = Category.all
    #gon.str = 'Hello World'
  end

  def create
    @account = Account.new
    get_params
    if @account.save
      redirect_to history_path("#{@account.year}-#{@account.month}",
                   start_date: "#{@account.year}-#{@account.month}-1")
    else
      redirect_to "/home"
    end
  end

  def edit
    @account = Account.find(params[:id])
    @categories = Category.all
  end

  def update
    @account = Account.find(params[:id])
    get_params
    if @account.save
      redirect_to history_path("#{@account.year}-#{@account.month}",
                   start_date: "#{@account.year}-#{@account.month}-1")
    else
      redirect_to "/home"
    end
  end

  def destroy
    account = Account.find(params[:id])
    account.destroy
    redirect_to accounts_path
  end

  private

    def set_sum_money
      @sum_money = @accounts.total_amount
      @sum_money_red = @accounts.only_red.total_amount
      @sum_money_yellow = @accounts.only_yellow.total_amount
      @sum_money_green = @accounts.only_green.total_amount
    end

    def get_params
      @account.date = params[:date]
      @account.year = params[:date].to_date.year
      @account.month = params[:date].to_date.month
      @account.day = params[:date].to_date.day
      @account.category = params[:category]
      @account.purpose = params[:purpose]
      @account.money = params[:money]
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def create
    category = Category.new
    category.name = params[:add_category]
    if category.save
      redirect_to categories_path
    else
      redirect_to "/home"
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to categories_path
  end 
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.js
    end

    @today = Date.today

    @recently_ym = []
    @recently = []
    @hash_sums = {}
    @hash_sums["sums"] = []
    @hash_sums["sums_red"] = []
    @hash_sums["sums_yellow"] = []
    @hash_sums["sums_green"] = []
    13.times do |i|
      year = (@today - i.month).year
      month = "%02d" % (@today - i.month).month
      sum = Account.search_by_year_and_month(year, month).total_amount
      @recently_ym << [year, month, sum]
      @recently << "#{year}年 #{month}月"
      @hash_sums["sums"] << sum
      @hash_sums["sums_red"] << Account.search_by_year_and_month(year, month).only_red.total_amount
      @hash_sums["sums_yellow"] << Account.search_by_year_and_month(year, month).only_yellow.total_amount
      @hash_sums["sums_green"] << Account.search_by_year_and_month(year, month).only_green.total_amount
    end
    gon.labels = @recently.reverse
    gon.sums = @hash_sums["sums"].reverse
    gon.sums_red = @hash_sums["sums_red"].reverse
    gon.sums_yellow = @hash_sums["sums_yellow"].reverse
    gon.sums_green = @hash_sums["sums_green"].reverse
    gon.sums_max = @hash_sums["sums"] .max
  end

  def show
    respond_to do |format|
      format.html
      format.csv
    end

    @categories = Category.all
    begin
      @today = Date.today
      year_month = params[:id].split("-")
      @year = year_month[0]
      @month = year_month[1]
      @current_date = "#{@year}/#{@month}/1".to_date
      if @today < @current_date || @current_date < @today.ago(10.year)
        redirect_to accounts_path
      end

      @prev_m = @current_date.prev_month
      @next_m = @current_date.next_month
      @accounts = Account.search_by_year_and_month(@year, @month)
      set_sum_money
    rescue
      redirect_to accounts_path
    end
  end

  private

    def set_sum_money
      @sum_money = @accounts.total_amount
      @sum_money_red = @accounts.only_red.total_amount
      @sum_money_yellow = @accounts.only_yellow.total_amount
      @sum_money_green = @accounts.only_green.total_amount
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/_calendar.html.erb
<%= month_calendar do |date| %>
  <a class="test_day"><%= date.day %></a>
  <i hidden><%= date.to_s.gsub(/-/,'/') %></i>
<% end %>

app/views/accounts/edit.html.erb
<section class="account_edit">
  <h1>家計簿の編集</h1>
  <div class="account-form">
    <%= form_tag account_path(@account.id), method: "put" do %>
      <table class="form_table" cellspacing="0" border="2">
        <tr class="columns">
          <td>日付</td>
          <td>カテゴリー</td>
          <td>目的</td>
          <td>金額</td>
        </tr>
        <tr>
          <td><input type="text" id="text1" name="date" value="<%= @account.date.to_s.gsub(/-/,'/') %>"></td>
          <td>
            <select name="category">
              <option value="">選択して下さい</option>
              <% @categories.each do |category| %>
                <option <%= "selected" if @account.category == category.name %>><%= category.name %></option>
              <% end %>
            </select>
          </td>
          <td>
            <select name="purpose">
              <option value="">選択して下さい</option>
              <option <%= "selected" if @account.purpose == "生活費" %>>生活費</option>
              <option <%= "selected" if @account.purpose == "趣味・娯楽" %>>趣味・娯楽</option>
              <option <%= "selected" if @account.purpose == "仕事・勉強" %>>仕事・勉強</option>
            </select>
          </td>
          <td><input type="text" id="test3" name="money" value="<%= @account.money %>"></td>
        </tr>
      </table>
      <input type="submit" value="再入力" class="submit_button">
    <% end %>
  </div>
</section>

app/views/accounts/index.html.erb
<section class="account_index">
  <h1>家計簿App index</h1>
  <p>今日の日付：<%= @today.to_s.gsub(/-/,'/') %></p>
  <div class="test"></div>

  <div class="account-form">
    <%= form_tag request.url do %>
      <table class="form_table" cellspacing="0" border="2">
        <tr class="columns">
          <td>日付</td>
          <td>カテゴリー</td>
          <td>目的</td>
          <td>金額</td>
        </tr>
        <tr>
          <td><input type="text" name="date" value="" id="date"></td>
          <td>
            <select name="category">
              <option value="">選択して下さい</option>
              <% @categories.each do |category| %>
                <option><%= category.name %></option>
              <% end %>
            </select>
          </td>
          <td>
            <select name="purpose">
              <option value="">選択して下さい</option>
              <option>生活費</option>
              <option>趣味・娯楽</option>
              <option>仕事・勉強</option>
            </select>
          </td>
          <td><input type="text" name="money"></td>
        </tr>
      </table>
      <input type="submit" value="入力" class="submit_button">
    <% end %>
    <div id="calendar">
      <%= render 'share/calendar' %>
    </div>
  </div>
  <div class="date_tables">
    <table class="data_table">
      <tr>
        <td colspan="4"><h4><%= link_to "<< ", history_path("#{@year}-#{@month.to_i - 1}") %>今月のお買い物データ</h4></td>
      </tr>
      <tr class="columns">
        <td>日付</td>
        <td>カテゴリー</td>
        <td>目的</td>
        <td>金額</td>
      </tr>
      <% @accounts.each do |account| %>
        <tr class="account_tr">
          <td class="date"><%= account.date.to_s.gsub(/-/,'/')  %></td>
          <td class="category"><%= account.category %></td>
          <td class="purpose"><%= account.purpose %></td>
          <td class="money"><%= "¥#{account.money.to_s(:delimited)}" %></td>
          <td>
            <%= link_to account_path(account.id), method: "delete", style: "color: gray;" do %>
              <i class="fa fa-trash-alt"></i>
            <% end %>
            <%= link_to edit_account_path(account.id), style: "color: gray;" do %>
              <i class="fa fa-cog"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr id="sum_tr">
        <td></td>
        <td></td>
        <td><i id="sum_td">合計 :</i></td>
        <td id="sum_money"><%= "¥#{@sum_money.to_s(:delimited)}" %></td>
      </tr>
    </table>
    =========================================
    <br>
    <table class="summary_table">
      <tr>
        <td colspan="2"><h4>目的ごとサマリー</h4></td>
      </tr>
      <tr class="columns">
        <td>目的</td>
        <td>合計金額</td>
      </tr>
      <tr>
        <td class="purpose">趣味・娯楽</td>
        <td><%= "¥#{@sum_money_red.to_s(:delimited)}" %></td>
      </tr>
      <tr>
        <td class="purpose">生活費</td>
        <td><%= "¥#{@sum_money_yellow.to_s(:delimited)}" %></td>
      </tr>
      <tr>
        <td class="purpose">仕事・勉強</td>
        <td><%= "¥#{@sum_money_green.to_s(:delimited)}" %></td>
      </tr>
      <tr>
      </tr>
    </table>
  </div>
</section>

app/views/accounts/index.js.erb
$('#calendar').html("<%= escape_javascript(render 'calendar') %>")

app/views/categories/index.html.erb
<section class="category_index">
  <h1>カテゴリー 一覧</h1>
  <p>普段買い物するカテゴリーをカスタマイズしましょう</p>

  <div class="form_of_category">
    <%= form_tag request.url do %>
      <input type="text" name="add_category">
      <input type="submit" value="追加">
    <% end %>
  </div>

  <table class="category_list" cellspacing="0" border="2">
    <tr class="columns">
      <td>カテゴリー名</td>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %>
          <%= link_to category_path(category.id), method: "delete", style: "color: gray;" do %>
            <i class="fa fa-trash-alt"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</section>

app/views/histories/_graph.html.erb
<h1>棒グラフ</h1>
<canvas id="myBarChart" width="800"></canvas>
<script>
var ctx = document.getElementById("myBarChart");
var myBarChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: gon.labels,
    datasets: [
      {
        label: '毎月の合計金額',
        data: gon.sums,
        backgroundColor: "rgba(130,201,169,0.5)"
      }
    ]
  },
  options: {
    responsive: false,
    title: {
      display: true,
      text: '過去1年間の分析'
    },
    scales: {
      yAxes: [{
        ticks: {
          suggestedMax: gon.sums_max,
          suggestedMin: 0,
          stepSize: gon.sums_max / 10,
          callback: function(value, index, values){
            return  '¥' + value
          }
        }
      }]
    },
  }
});
</script>

app/views/histories/_graph2.html.erb
<h1></h1>
<canvas id="myBarChart" width="800"></canvas>
<script>
var ctx = document.getElementById("myBarChart");
var myBarChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: gon.labels,
    datasets: [
      {
          label: '趣味・娯楽',
          data: gon.sums_red,
          backgroundColor: "rgba(219,39,91,0.5)"
        },{
          label: '生活費',
          data: gon.sums_yellow,
          backgroundColor: "rgba(255,183,76,0.5)"
        },{
          label: '仕事・勉強',
          data: gon.sums_green,
          backgroundColor: "rgba(176,237,148,0.9)"
        }
    ]
  },
  options: {
    responsive: false,
    title: {
      display: true,
      text: '過去1年間の分析'
    },
    scales: {
      yAxes: [{
        ticks: {
          suggestedMax: gon.sums_max,
          suggestedMin: 0,
          stepSize: gon.sums_max / 10,
          callback: function(value, index, values){
            return  '¥' + value
          }
        }
      }]
    },
  }
});
</script>

app/views/histories/index.html.erb
<section class="history_index">
  <h1>履歴</h1>
  <p>Find me in app/views/histories/index.html.erb</p>

  <div class="history_list">
    <table cellspacing="0" border="2">
      <% @recently_ym.each do |ym| %>
        <tr>
          <td>
            <% year = ym[0] %>
            <% month = ym[1] %>
            <% sum = ym[2] %>
            <%= link_to "#{year}年 #{month}月",
                        history_path("#{ym[0]}-#{ym[1]}", start_date: "#{ym[0]}-#{ym[1]}-1") %>
          </td>
          <td class="monthly_sum">
            <%= "¥#{sum.to_s(:delimited)}" %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <h1>毎月の集計</h1>
  <div class="graph_button">
    <ul>
      <li>
        <%= button_to '合計金額', request.url,
                                   { params: {graph_switch: '1' }, method: :get, remote: true } %>
      </li>
      <li>
        <%= button_to '目的別の合計', request.url,
                                    { params: {graph_switch: '2' }, method: :get, remote: true } %>
      </li>
    </ul>
  </div>
  <div class="display_graph">
    <%= render params[:graph_switch] == "2" ? 'graph2' : 'graph' %>
  </div>
  <div>
    ※ グラフが表示されない場合
    <ul>
      <li>
        <%= button_to 'グラフ表示', request.url, method: :get %>
      </li>
    </ul>
  </div>
</section>

app/views/histories/index.js.erb
$('.display_graph').html("<%= escape_javascript(render params[:graph_switch] == "2" ? 'graph2' : 'graph') %>")

app/views/histories/show.csv.erb
日付,カテゴリー,目的,金額
<% @accounts.each do |account| %>
  <%= [account.date.to_s.gsub(/-/,'/'), account.category, account.purpose, account.money].join(',') %>
<% end %>

app/views/histories/show.html.erb
<section class="history_show">
  <h1><%= "#{@year}年 #{@month}月"%></h1>

  <div class="account-form">
    <%= form_tag accounts_path do %>
      <table class="form_table" cellspacing="0" border="2">
        <tr class="columns">
          <td>日付</td>
          <td>カテゴリー</td>
          <td>目的</td>
          <td>金額</td>
        </tr>
        <tr>
          <td><input type="text" name="date" value="" id="date"></td>
          <td>
            <select name="category">
              <option value="">選択して下さい</option>
              <% @categories.each do |category| %>
                <option><%= category.name %></option>
              <% end %>
            </select>
          </td>
          <td>
            <select name="purpose">
              <option value="">選択して下さい</option>
              <option>生活費</option>
              <option>趣味・娯楽</option>
              <option>仕事・勉強</option>
            </select>
          </td>
          <td><input type="text" name="money"></td>
        </tr>
      </table>
      <input type="submit" value="入力" class="submit_button">
    <% end %>
    <div id="calendar">
      <%= render 'share/calendar' %>
    </div>
  </div>

  <div class="date_tables">
    <table class="data_table">
      <tr>
        <td colspan="4">
          <h4><%= link_to "<<", history_path("#{@prev_m.year}-#{@prev_m.month}", start_date: @prev_m) %>
            <%= "#{@year}年 #{@month}月 のお買い物データ"%>
            <%= link_to ">>", history_path("#{@next_m.year}-#{@next_m.month}", start_date: @next_m) unless "#{@year}/#{@month}" == "#{@today.year}/#{@today.month}" %>
          </h4>
        </td>
      </tr>
      <tr class="columns">
        <td>日付</td>
        <td>カテゴリー</td>
        <td>目的</td>
        <td>金額</td>
      </tr>
      <% @accounts.each do |account| %>
        <tr class="account_tr">
          <td class="date"><%= account.date.to_s.gsub(/-/,'/') %></td>
          <td class="category"><%= account.category %></td>
          <td class="purpose"><%= account.purpose %></td>
          <td class="money"><%= "¥#{account.money.to_s(:delimited)}" %></td>
          <td>
            <%= link_to account_path(account.id), method: "delete", style: "color: gray;" do %>
              <i class="fa fa-trash-alt"></i>
            <% end %>
            <%= link_to edit_account_path(account.id), style: "color: gray;" do %>
              <i class="fa fa-cog"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr id="sum_tr">
        <td></td>
        <td></td>
        <td><i id="sum_td">合計 :</i></td>
        <td id="sum_money"><%= "¥#{@sum_money.to_s(:delimited)}" %></td>
      </tr>
    </table>
    <h3>データをcsvファイルでダウンロードする場合はこちら</h3>
    <%= button_to 'ダウンロード', history_path("#{@year}-#{@month}") + ".csv" , method: :get %>
    =========================================
    <br>
    <table class="summary_table">
      <tr>
        <td colspan="2"><h4>目的ごとサマリー</h4></td>
      </tr>
      <tr class="columns">
        <td>目的</td>
        <td>合計金額</td>
      </tr>
      <tr>
        <td class="purpose">趣味・娯楽</td>
        <td><%= "¥#{@sum_money_red.to_s(:delimited)}" %></td>
      </tr>
      <tr>
        <td class="purpose">生活費</td>
        <td><%= "¥#{@sum_money_yellow.to_s(:delimited)}" %></td>
      </tr>
      <tr>
        <td class="purpose">仕事・勉強</td>
        <td><%= "¥#{@sum_money_green.to_s(:delimited)}" %></td>
      </tr>
      <tr>
      </tr>
    </table>
  </div>

</section>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">家計簿App</a>
      </div>
      <ul class="nav navbar-nav">
        <li class=<%= "active" if request.path == accounts_path %>><%= link_to 'Index', accounts_path %></li>
        <li class=<%= "active" if request.path == categories_path %>><%= link_to 'カテゴリー編集', categories_path %></li>
        <li class=<%= "active" if request.path.include?("histories") %>><%= link_to '履歴', histories_path %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KakeiboApp</title>
    <%= csrf_meta_tags %>

    <%= include_gon(init: true) %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/share/_calendar.html.erb
<%= month_calendar do |date| %>
  <a class="test_day"><%= date.day %></a>
  
  <i hidden><%= date.to_s.gsub(/-/,'/') %></i>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <table class="table table-striped">
    <caption>
      <div class="calendar-heading">
         <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view if request.path == accounts_path %>
        <span class="calendar-title" style="font-size: 30px;">
          <%= " #{start_date.year}年" %> <%= "#{start_date.month}月" %>
          </span>
         <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view  if request.path == accounts_path %>
      </div>
    </caption>
    <thead>
      <tr>
        <% ["月","火","水","木","金","土","日"].each do |day| %>
          <th><%= day %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>